name: Scrape and Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flask pandas pytz selenium webdriver-manager lxml openpyxl

    - name: Build Docker container
      run: docker build -t flask-app .

    - name: Run Docker container
      id: run_container
      run: docker run -d -p 8000:8000 --name flask_app_container flask-app

    - name: Wait for Flask to be ready
      run: sleep 20

    - name: Check and log container status
      run: |
        CONTAINER_STATUS=$(docker ps -a -f name=flask_app_container --format "{{.Status}}")
        echo "Container Status: $CONTAINER_STATUS"
        if [[ "$CONTAINER_STATUS" != "Up "* ]]; then
          echo "Container logs:"
          docker logs flask_app_container
          exit 1
        fi

    - name: Run Selenium script
      run: docker exec flask_app_container python scrape.py

    - name: Verify file changes
      run: |
        echo "Checking for changes in scraped_data.xlsx..."
        if git status --porcelain | grep -q scraped_data.xlsx; then
          echo "Changes detected in scraped_data.xlsx"
        else
          echo "No changes detected in scraped_data.xlsx"
          exit 1

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add scraped_data.xlsx
        git commit -m 'Update data'
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/nayan-khemka/ScrapingSecuredWebsite.git
